export const projects = [
  {
    title: 'Shareme App Project',
    description: "This is  a Full Stack Application that I built with  React, Next.js, Zustand & Sanity in backend. The App is called shareme and it is a simple video social media app that allows users to post interesting videos that happened in their lives.",
      image: '/images/1.jpg',
      tags: ['React.js', 'Next.js', 'Zustand', 'Sanity'],
    source: 'https://marcelino-dev-shareme-app.vercel.app',
    visit: 'https://marcelino-dev-shareme-app.vercel.app',
    id: 0,
  },
  {
    title: 'Borcelle Kitchen Project',
    description: "This is  a Full Stack Application that I built with  Angular13 & Typescript in Front-End, Nodejs & MongoDB in backend. The App is called Borcelle Kitchen and it is a video Food app that allows users to order their favorite foods.",
      image: '/images/L.png',
      tags: ['Angular13', 'Typescript', 'Nodejs', 'MongoDB'],
    source: 'https://marcelinodev-kitchen.herokuapp.com/',
    visit: 'https://marcelinodev-kitchen.herokuapp.com/',
    id: 1,
  },
  {
    title: 'E-Commerce',
    description:"In This project I used advanced React & JavaScript topics, as well as how to use Stripe for card transactions. Feel free to explore this unique and complex Webshop App",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://marcelodev-webshop.vercel.app/',
    visit: 'https://marcelodev-webshop.vercel.app/',
    id: 2,
  },
  {
    title: 'WebRTC App',
    description: "This is a React Video Chat Application using WebRTC.",
      image: '/images/3.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://marcelino-dev-video-chat.netlify.app/',
    visit: 'https://marcelino-dev-video-chat.netlify.app/',
    id: 3,
  },
  {
    title: 'Discord-Clone',
    description: "This is a full stack web app with a few complex functionalities such as: The ability to add a channel, send and delete message, and have a responsive design",
    image: '/images/4.png',
    tags: ['React', 'Redux Toolkit', 'TailwindCSS', 'Firebase'],
    source: 'https://marcelodev-discord.vercel.app/',
    visit: 'https://marcelodev-discord.vercel.app/',
    id: 4,
  },
  {
    title: 'React Native - NFT Market',
    description: "This is a React Native App with a modern UI/UX",
    image: '/images/6.png',
    tags: ['React Native', 'Cryptocurrency', 'NFT Market'],
    source: 'https://marcelodev-nft.on.fleek.co/',
    visit: 'https://marcelodev-nft.on.fleek.co/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey in High School', },
  { year: 2017, text: 'I began to learn advanced programming', },
  { year: 2018, text: 'I started my journey making real-world projects ', },
  { year: 2019, text: 'Shared my projects with the world', },
  { year: 2020, text: 'Started my journey at University', },
];